Task 3
WhatTheAncient/TestGuru pull request #3
Opened 2021-12-10 15:11 UTC by WhatTheAncient

С помощью интерфейса запросов ActiveRecord:

Создайте набор начальных данных для всех существующих моделей в файле db/seeds.rb

Создайте инстанс-метод в модели User, который принимает в качестве аргумента значение уровня сложности и возвращает список всех Тестов, которые проходит или когда-либо проходил Пользователь на этом уровне сложности

Создайте метод класса в модели Test, который возвращает отсортированный по убыванию массив названий всех Тестов у которых Категория называется определённым образом (название категории передается в метод в качестве аргумента).

2021-12-11 13:27 UTC, VidgarVii requested changes

2021-12-11 13:27 UTC, VidgarVii commented on app/models/test.rb
> +  end
для удобства чтения и редактирования можно переносить зачейненные вызовы вот так:
```ruby
  joins(...)
    .where(...)
    .order(...)
    .pluck(...)
```

2021-12-11 13:27 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins("JOIN categories ON categories.id = tests.category_id").where("categories.title = ?", category).order("tests.level DESC")
лучше всего, где это возможно, использовать "хеш-синтаксис" 
```ruby
  .where(categories: { title: title })
  .order(tests: :desc)
```

обычно это лаконичней и легче править

2021-12-11 13:27 UTC, VidgarVii commented on app/models/user.rb
> +
По ДЗ должен быть 1 метод. Какой надо проверять?

2021-12-11 13:27 UTC, VidgarVii commented on app/models/user.rb
> +  end
в основном замечания теже что выше. Очень сложно разобрать какой тут знак ? за что отвечает.
можно еще так 
where("categories.title = :title", title: category_title)
Но хеш всегда лучше

2021-12-11 13:27 UTC, VidgarVii commented on app/models/test.rb
> +  def self.tests_with_category(category)
По названию параметра складывается ощущение что метод принимает объект category. А не categories.title

2021-12-11 13:27 UTC, VidgarVii commented on db/migrate/20211209144216_create_questions.rb
> +      t.string :title, limit: 100, null: false
убери этот лимит. Он нам не к чему

2021-12-11 13:27 UTC, VidgarVii commented on db/migrate/20211210135527_create_results.rb
> +      t.boolean :finished, null: false, default: false
Не думаю что эти поля started и finished понадобятся. Эту задачу будет решать не много по другому. Хотя...

2021-12-11 13:27 UTC, VidgarVii commented on db/seeds.rb
> +  { title: 'Discrete Math', level: 3, category_id: 3, author_id: 1 },
"хардкодить" `id` - не очень хорошая затея
такой "сид" невозможно накатить на существующую базу, ведь там id могут быть заняты другими записями или вовсе отсутствовать
правильней воспользоваться тем, что метод `create` возвращает созданные записи

2021-12-11 13:27 UTC, VidgarVii commented on db/seeds.rb
> +Question.create(questions)
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2021-12-11 13:52 UTC, WhatTheAncient commented on app/models/user.rb
> +
Тот который возвращает сумму двух других. Я решил что в дальнейшем может понадобиться как вывод только начатых так и вывод только законченных. Если нужно, соединю, только скажите

2021-12-12 12:56 UTC, VidgarVii commented on app/models/user.rb
> +
мы не будем этим всем пользоваться
Согласно ДЗ нужен 1 метод который вернёт список всех Тестов, которые **проходит или когда-либо проходил** Пользователь на этом уровне сложности
У тебя сейчас лишняя сложность в коде. 
started и finished тоже можно убрать

2021-12-12 12:56 UTC, VidgarVii commented on app/models/user.rb
> +
но в целом код хорошо написал. Но надо придерживаться плана. И делать то что указано в задаче. Это важно
YAGNI

2021-12-13 08:23 UTC, VidgarVii commented on app/models/test.rb
> +        .order(tests: :desc)
нам нужен pluck. По ДЗ надо вернуть массив названий тестов

2021-12-13 08:23 UTC, VidgarVii commented on db/seeds.rb
> +Test.create!(tests).each { |test| tests_id << test.id }
можно воспользоваться тем, что метод `create` возвращает созданные записи
и не придется итерировать созданные тесты

кстати для получения всех ид есть метод .ids

2021-12-14 17:05 UTC, merged