Task 4
WhatTheAncient/TestGuru pull request #4
Opened 2021-12-15 17:51 UTC by WhatTheAncient

Определите ассоциации в моделях:
Между Тестами и Категориями
Между Тестами и Вопросами
Между Вопросами и Ответами
Между Тестами и проходящими их Пользователями (учесть, что один и тот же тест могут проходить несколько пользователей одновременно)
Между Тестом и автором (Пользователем), который его создал.

2021-12-16 08:10 UTC, VidgarVii requested changes

2021-12-16 08:10 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers, dependent: :destroy
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2021-12-16 08:10 UTC, VidgarVii commented on app/models/user.rb
> +  belongs_to :test
юзер ни кому не принадлежит

2021-12-16 08:10 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :users, through: :results
не хвататет dependent 
https://makandracards.com/makandra/32175-don-t-forget-automatically-remove-join-records-on-has_many-through-associations

2021-12-17 08:11 UTC, VidgarVii requested changes

2021-12-17 08:11 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers, dependent: :destroy
не исправил

2021-12-17 08:11 UTC, VidgarVii commented on app/models/test.rb
> +
не нужны тут отступы https://github.com/rubocop/ruby-style-guide#empty-lines-around-bodies

2021-12-17 08:11 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :users, through: :results, dependent: :destroy
небольшой [пост](https://makandracards.com/makandra/32175-don-t-forget-automatically-remove-join-records-on-has_many-through-associations) с рекомендацией относительно подобного случая

2021-12-17 08:11 UTC, VidgarVii commented on app/models/test.rb
> +    Category.find_by(title: category_title)
по дз надо вернуть массив название тестов

2021-12-17 08:11 UTC, VidgarVii commented on app/models/user.rb
> +
нет собственных созданных тестов?

2021-12-17 08:11 UTC, VidgarVii commented on app/models/user.rb
> +    self.tests
тут можно не писать self

2021-12-17 08:11 UTC, VidgarVii commented on app/models/user.rb
>    def get_tests_history(level) #Returns started and finished tests
приставки get_  в руби не принято писать https://github.com/rubocop/ruby-style-guide#accessor_mutator_method_names

2021-12-17 08:11 UTC, VidgarVii commented on db/migrate/20211210135527_create_results.rb
> +      t.belongs_to :test, null:false, foreign_key: true
пробельчики

2021-12-17 08:14 UTC, WhatTheAncient commented on app/models/test.rb
> +    Category.find_by(title: category_title)
Так эта функция и возвращает массив названий тестов, там же pluck дальше

2021-12-17 15:00 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :created_tests, inverse_of: :author, class_name: 'Test', foreign_key: 'author_id'
что будет если удалить юзера?

2021-12-19 08:19 UTC, merged